/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlgoUeb2;

import org.junit.Assert;
import org.junit.Test;

public class SinglyLikedTest {

    SinglyLinkedList<Student> test = new SinglyLinkedList<Student>();

    private static final Student student1 = new Student("Mark", "Something", 83, 7373);
    private static final Student student2 = new Student("Carl", "SomethingElse", 38, 3737);
    private static final Student student3 = new Student("Huseyin", "SomethingNew", 35, 2937);

    @Test
    public void goodAddFirstAndGetTest() {
        Assert.assertNull(test.get(0));
        test.addFirst(student1);
        Assert.assertEquals(student1, test.get(0));
        test.addFirst(student2);
        Assert.assertEquals(student2, test.get(0));
        test.addFirst(student1);
        Assert.assertEquals(student1, test.get(0));
        Assert.assertEquals(student2, test.get(1));
        Assert.assertEquals(student1, test.get(2));
    }

    @Test
    public void badAddFirstAndGetTest() {
        test.addFirst(student1);
        Assert.assertNotNull(test.get(0));
        test.addFirst(student2);
        Assert.assertNotEquals(student1, test.get(0));
        test.addFirst(student3);
        Assert.assertNotEquals(student1, test.get(0));
        Assert.assertNotEquals(student2, test.get(0));
    }

    @Test
    public void goodAddLastAndGetTest() {
        test.addLast(student1);
        Assert.assertEquals(student1, test.get(0));
        test.addLast(student2);
        Assert.assertEquals(student1, test.get(0));
        Assert.assertEquals(student2, test.get(1));
    }

    @Test
    public void goodRemoveTest() throws Exception {
        test.add(student1);
        test.add(student2);
        test.add(student3);
        test.remove(0);
        Assert.assertEquals(student2, test.get(0));
    }
}
