/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AlgoUeb2;

import AlgoUeb2.lists.DoublyLinkedList;

public class App {

    public static void main(String[] args){

    }
}
